### Multiclass Classification

In [4]:
import pandas as pd
from sklearn.metrics import confusion_matrix,classification_report

In [5]:
df=pd.read_csv('iris (1).csv')
df.shape

(150, 5)

In [6]:
df.head()

sepal_length  sepal_width  petal_length  petal_width        class
0           5.1          3.5           1.4          0.2  Iris-setosa
1           4.9          3.0           1.4          0.2  Iris-setosa
2           4.7          3.2           1.3          0.2  Iris-setosa
3           4.6          3.1           1.5          0.2  Iris-setosa
4           5.0          3.6           1.4          0.2  Iris-setosa

In [7]:
df.isnull().sum()

sepal_length    0
sepal_width     0
petal_length    0
petal_width     0
class           0
dtype: int64

In [8]:
df.columns

Index(['sepal_length', 'sepal_width', 'petal_length', 'petal_width', 'class'], dtype='object')

In [9]:
df['class'].value_counts(normalize=True)

Iris-setosa        0.333333
Iris-virginica     0.333333
Iris-versicolor    0.333333
Name: class, dtype: float64

In [10]:
df['class'].value_counts()

Iris-setosa        50
Iris-virginica     50
Iris-versicolor    50
Name: class, dtype: int64

In [11]:
x=df[['sepal_length', 'sepal_width', 'petal_length', 'petal_width']]
y=df['class']

In [12]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,train_size=0.8,random_state=123)

In [13]:
print(x_train.shape)
print(y_test.shape)
print(y_train.shape)
print(x_test.shape)

(120, 4)
(30,)
(120,)
(30, 4)


In [14]:
from sklearn.tree import DecisionTreeClassifier
dt=DecisionTreeClassifier()
dt.fit(x_train,y_train)

DecisionTreeClassifier()

In [15]:
# prediction on test data
print('****** prediction on test data *******')
predict_test = dt.predict(x_test)

# Actual Value : y_test
# prediction : predict_test
print('Confusion Matrix')
print(confusion_matrix(y_test, predict_test))

print('---------------------------------------------------')
print('Classification Report')
print(classification_report(y_test, predict_test))

****** prediction on test data *******
Confusion Matrix
[[13  0  0]
 [ 0  6  0]
 [ 0  0 11]]
---------------------------------------------------
Classification Report
                 precision    recall  f1-score   support

    Iris-setosa       1.00      1.00      1.00        13
Iris-versicolor       1.00      1.00      1.00         6
 Iris-virginica       1.00      1.00      1.00        11

       accuracy                           1.00        30
      macro avg       1.00      1.00      1.00        30
   weighted avg       1.00      1.00      1.00        30



In [16]:
# prediction on train data
print('****** prediction on train data *******')
predict_train = dt.predict(x_train)

# Actual Value : y_train
# prediction : predict_train
print('Confusion Matrix')
print(confusion_matrix(y_train, predict_train))

print('---------------------------------------------------')
print('Classification Report')
print(classification_report(y_train, predict_train))

****** prediction on train data *******
Confusion Matrix
[[37  0  0]
 [ 0 44  0]
 [ 0  0 39]]
---------------------------------------------------
Classification Report
                 precision    recall  f1-score   support

    Iris-setosa       1.00      1.00      1.00        37
Iris-versicolor       1.00      1.00      1.00        44
 Iris-virginica       1.00      1.00      1.00        39

       accuracy                           1.00       120
      macro avg       1.00      1.00      1.00       120
   weighted avg       1.00      1.00      1.00       120



### Regression Concept

In [17]:
df=pd.read_csv('wine.csv')
df.shape

(25, 7)

In [18]:
df.head()

Year   Price  WinterRain     AGST  HarvestRain  Age  FrancePop
0  1952  7.4950         600  17.1167          160   31  43183.569
1  1953  8.0393         690  16.7333           80   30  43495.030
2  1955  7.6858         502  17.1500          130   28  44217.857
3  1957  6.9845         420  16.1333          110   26  45152.252
4  1958  6.7772         582  16.4167          187   25  45653.805

In [19]:
df.columns

Index(['Year', 'Price', 'WinterRain', 'AGST', 'HarvestRain', 'Age',
       'FrancePop'],
      dtype='object')

In [20]:
df.describe().T

count          mean          std         min         25%  \
Year          25.0   1965.800000     7.691987   1952.0000   1960.0000   
Price         25.0      7.067224     0.650341      6.2049      6.5188   
WinterRain    25.0    605.280000   132.277965    376.0000    536.0000   
AGST          25.0     16.509336     0.675397     14.9833     16.2000   
HarvestRain   25.0    148.560000    74.419464     38.0000     89.0000   
Age           25.0     17.200000     7.691987      5.0000     11.0000   
FrancePop     25.0  49694.436760  3665.270243  43183.5690  46583.9950   

                    50%         75%         max  
Year          1966.0000   1972.0000   1978.0000  
Price            7.1211      7.4950      8.4937  
WinterRain     600.0000    697.0000    830.0000  
AGST            16.5333     17.0667     17.6500  
HarvestRain    130.0000    187.0000    292.0000  
Age             17.0000     23.0000     31.0000  
FrancePop    50254.9660  52894.1830  54602.1930

In [21]:
df.isnull().sum()

Year           0
Price          0
WinterRain     0
AGST           0
HarvestRain    0
Age            0
FrancePop      0
dtype: int64

In [22]:
x=df[['WinterRain', 'AGST', 'HarvestRain', 'Age',
       'FrancePop']]
y=df['Price']

In [23]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,train_size=0.8,random_state=123)

In [24]:
print(x_train.shape)
print(y_test.shape)
print(y_train.shape)
print(x_test.shape)

(20, 5)
(5,)
(20,)
(5, 5)


In [25]:
from sklearn.tree import DecisionTreeRegressor
dt = DecisionTreeRegressor()
dt.fit(x_train, y_train)

DecisionTreeRegressor()

In [36]:
#Prediction using test data
predict_test=dt.predict(x_test)

In [49]:
from sklearn.metrics import mean_squared_error, mean_absolute_error
# test data
mae=mean_absolute_error(y_test, predict_test)
print('Mean Absolute Error is', mae)

mse = mean_squared_error(y_test, predict_test)
print('Mean Squared Error is', mse)

rmse=np.sqrt(mse)
print('Root Mean Squared Error is', rmse)

mape= np.mean(np.abs((y_test - predict_test)/y_test))*100
print('Root Mean absolute percentage error is', mape)

Mean Absolute Error is 0.5917399999999999
Mean Squared Error is 0.4659322779999998
Root Mean Squared Error is 0.6825923219609197
Root Mean absolute percentage error is 8.504983310148837


In [48]:
#MSE using numpy
import numpy as np
MSE = np.square(np.subtract(y_test,predict_test)).mean()
MSE

0.4659322779999998

### GridsearchCV

In [50]:
from sklearn.model_selection import GridSearchCV

In [51]:
df=pd.read_csv('iris (1).csv')

In [52]:
df.columns

Index(['sepal_length', 'sepal_width', 'petal_length', 'petal_width', 'class'], dtype='object')

In [53]:
x=df[['sepal_length', 'sepal_width', 'petal_length', 'petal_width']]
y=df[['class']]

In [54]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,train_size=0.8,random_state=123)

In [55]:
from xgboost import XGBClassifier
xgb=XGBClassifier()
xgb.fit(x_train,y_train)

/usr/local/lib/python3.7/site-packages/sklearn/utils/validation.py:63: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  return f(*args, **kwargs)


XGBClassifier(base_score=0.5, booster=None, colsample_bylevel=1,
              colsample_bynode=1, colsample_bytree=1, gamma=0, gpu_id=-1,
              importance_type='gain', interaction_constraints=None,
              learning_rate=0.300000012, max_delta_step=0, max_depth=6,
              min_child_weight=1, missing=nan, monotone_constraints=None,
              n_estimators=100, n_jobs=0, num_parallel_tree=1,
              objective='multi:softprob', random_state=0, reg_alpha=0,
              reg_lambda=1, scale_pos_weight=None, subsample=1,
              tree_method=None, validate_parameters=False, verbosity=None)

In [56]:
max_depth= 2,3,4,5,6
n_estimators= 20,50,80,100,200,500
learning_rate= 0.1,0.2,0.3,0.5

In [57]:
param_grid= {
    'learning_rate': [0.1,0.2,0.3,0.5],
    'n_estimators' : [20,50,80,100,200,500],
    'max_depth' : [2,3,4,5,6]
}

In [58]:
grid_search=GridSearchCV(estimator=xgb,param_grid=param_grid,n_jobs=-1)

In [59]:
grid_search.fit(x_train,y_train)

/usr/local/lib/python3.7/site-packages/sklearn/utils/validation.py:63: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  return f(*args, **kwargs)


GridSearchCV(estimator=XGBClassifier(base_score=0.5, booster=None,
                                     colsample_bylevel=1, colsample_bynode=1,
                                     colsample_bytree=1, gamma=0, gpu_id=-1,
                                     importance_type='gain',
                                     interaction_constraints=None,
                                     learning_rate=0.300000012,
                                     max_delta_step=0, max_depth=6,
                                     min_child_weight=1, missing=nan,
                                     monotone_constraints=None,
                                     n_estimators=100, n_jobs=0,
                                     num_parallel_tree=1,
                                     objective='multi:softprob', random_state=0,
                                     reg_alpha=0, reg_lambda=1,
                                     scale_pos_weight=None, subsample=1,
                                     tree_m

In [60]:
grid_search.best_estimator_

XGBClassifier(base_score=0.5, booster=None, colsample_bylevel=1,
              colsample_bynode=1, colsample_bytree=1, gamma=0, gpu_id=-1,
              importance_type='gain', interaction_constraints=None,
              learning_rate=0.1, max_delta_step=0, max_depth=2,
              min_child_weight=1, missing=nan, monotone_constraints=None,
              n_estimators=200, n_jobs=0, num_parallel_tree=1,
              objective='multi:softprob', random_state=0, reg_alpha=0,
              reg_lambda=1, scale_pos_weight=None, subsample=1,
              tree_method=None, validate_parameters=False, verbosity=None)

### Cross Validation

In [62]:
from sklearn.model_selection import cross_val_score
from xgboost import XGBClassifier
xgb=XGBClassifier()
xgb.fit(x_train,y_train)

/usr/local/lib/python3.7/site-packages/sklearn/utils/validation.py:63: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  return f(*args, **kwargs)


XGBClassifier(base_score=0.5, booster=None, colsample_bylevel=1,
              colsample_bynode=1, colsample_bytree=1, gamma=0, gpu_id=-1,
              importance_type='gain', interaction_constraints=None,
              learning_rate=0.300000012, max_delta_step=0, max_depth=6,
              min_child_weight=1, missing=nan, monotone_constraints=None,
              n_estimators=100, n_jobs=0, num_parallel_tree=1,
              objective='multi:softprob', random_state=0, reg_alpha=0,
              reg_lambda=1, scale_pos_weight=None, subsample=1,
              tree_method=None, validate_parameters=False, verbosity=None)

In [63]:
score = cross_val_score(xgb, x, y, cv=5)

/usr/local/lib/python3.7/site-packages/sklearn/utils/validation.py:63: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  return f(*args, **kwargs)
/usr/local/lib/python3.7/site-packages/sklearn/utils/validation.py:63: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  return f(*args, **kwargs)
/usr/local/lib/python3.7/site-packages/sklearn/utils/validation.py:63: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  return f(*args, **kwargs)
/usr/local/lib/python3.7/site-packages/sklearn/utils/validation.py:63: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  return

In [64]:
score

array([0.96666667, 0.96666667, 0.93333333, 0.93333333, 1.        ])

In [65]:
score.mean()

0.96

In [66]:
score.var()

0.0006222222222222219

In [68]:
score = cross_val_score(xgb, x, y, cv=10)

/usr/local/lib/python3.7/site-packages/sklearn/utils/validation.py:63: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  return f(*args, **kwargs)
/usr/local/lib/python3.7/site-packages/sklearn/utils/validation.py:63: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  return f(*args, **kwargs)
/usr/local/lib/python3.7/site-packages/sklearn/utils/validation.py:63: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  return f(*args, **kwargs)
/usr/local/lib/python3.7/site-packages/sklearn/utils/validation.py:63: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  return

In [69]:
print(score)
print(score.mean())
print(score.var())

[1.         0.93333333 1.         0.93333333 0.93333333 0.93333333
 0.93333333 0.93333333 1.         1.        ]
0.96
0.001066666666666666
